# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matteo/github/chaisse

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matteo/github/chaisse

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matteo/github/chaisse/CMakeFiles /home/matteo/github/chaisse/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matteo/github/chaisse/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named chaisse

# Build rule for target.
chaisse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chaisse
.PHONY : chaisse

# fast build rule for target.
chaisse/fast:
	$(MAKE) -f CMakeFiles/chaisse.dir/build.make CMakeFiles/chaisse.dir/build
.PHONY : chaisse/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

src/chaisse.o: src/chaisse.cpp.o

.PHONY : src/chaisse.o

# target to build an object file
src/chaisse.cpp.o:
	$(MAKE) -f CMakeFiles/chaisse.dir/build.make CMakeFiles/chaisse.dir/src/chaisse.cpp.o
.PHONY : src/chaisse.cpp.o

src/chaisse.i: src/chaisse.cpp.i

.PHONY : src/chaisse.i

# target to preprocess a source file
src/chaisse.cpp.i:
	$(MAKE) -f CMakeFiles/chaisse.dir/build.make CMakeFiles/chaisse.dir/src/chaisse.cpp.i
.PHONY : src/chaisse.cpp.i

src/chaisse.s: src/chaisse.cpp.s

.PHONY : src/chaisse.s

# target to generate assembly for a file
src/chaisse.cpp.s:
	$(MAKE) -f CMakeFiles/chaisse.dir/build.make CMakeFiles/chaisse.dir/src/chaisse.cpp.s
.PHONY : src/chaisse.cpp.s

src/cli/client.o: src/cli/client.cpp.o

.PHONY : src/cli/client.o

# target to build an object file
src/cli/client.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/cli/client.cpp.o
.PHONY : src/cli/client.cpp.o

src/cli/client.i: src/cli/client.cpp.i

.PHONY : src/cli/client.i

# target to preprocess a source file
src/cli/client.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/cli/client.cpp.i
.PHONY : src/cli/client.cpp.i

src/cli/client.s: src/cli/client.cpp.s

.PHONY : src/cli/client.s

# target to generate assembly for a file
src/cli/client.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/cli/client.cpp.s
.PHONY : src/cli/client.cpp.s

src/com/connection.o: src/com/connection.cpp.o

.PHONY : src/com/connection.o

# target to build an object file
src/com/connection.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/com/connection.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/com/connection.cpp.o
.PHONY : src/com/connection.cpp.o

src/com/connection.i: src/com/connection.cpp.i

.PHONY : src/com/connection.i

# target to preprocess a source file
src/com/connection.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/com/connection.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/com/connection.cpp.i
.PHONY : src/com/connection.cpp.i

src/com/connection.s: src/com/connection.cpp.s

.PHONY : src/com/connection.s

# target to generate assembly for a file
src/com/connection.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/com/connection.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/com/connection.cpp.s
.PHONY : src/com/connection.cpp.s

src/srv/server.o: src/srv/server.cpp.o

.PHONY : src/srv/server.o

# target to build an object file
src/srv/server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/srv/server.cpp.o
.PHONY : src/srv/server.cpp.o

src/srv/server.i: src/srv/server.cpp.i

.PHONY : src/srv/server.i

# target to preprocess a source file
src/srv/server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/srv/server.cpp.i
.PHONY : src/srv/server.cpp.i

src/srv/server.s: src/srv/server.cpp.s

.PHONY : src/srv/server.s

# target to generate assembly for a file
src/srv/server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/srv/server.cpp.s
.PHONY : src/srv/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... chaisse"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... src/chaisse.o"
	@echo "... src/chaisse.i"
	@echo "... src/chaisse.s"
	@echo "... src/cli/client.o"
	@echo "... src/cli/client.i"
	@echo "... src/cli/client.s"
	@echo "... src/com/connection.o"
	@echo "... src/com/connection.i"
	@echo "... src/com/connection.s"
	@echo "... src/srv/server.o"
	@echo "... src/srv/server.i"
	@echo "... src/srv/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

